server:
  port: 8180
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: iam-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"   # Imports configuration data from a config server when available
  cloud:
    config:
      uri: http://localhost:8071
      request-connect-timeout: 5000   # Timeout on waiting to connect to the config server (ms)
      request-read-timeout: 5000      # Timeout on waiting to read configuration data from the config server (ms)
      fail-fast: true                 # In production, set to true. Makes a failure to connect to the config server fatal
      retry:
        max-attempts: 6
        initial-interval: 1000        # Initial retry interval for backoff (ms)
        max-interval: 2000            # Maximum retry interval for backoff (ms)
        multiplier: 1.1               # Multiplier to compute the next interval
    function:
      definition: consumer
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeDecoding: true
      function:
        definition: consumer;producer;producerTest
      kafka:
        binder:
          brokers: http://localhost:9092
        bindings:
          producer-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: com.ailegorreta.commons.event.EventDTOSerializer
          producerTest-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: com.ailegorreta.commons.event.EventDTOSerializer
          consumer-in-0:
            consumer:
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: com.ailegorreta.commons.event.EventDTODeSerializer
      bindings:
        producer-out-0:
          destination: audit
        producerTest-out-0:
          destination: bup
        consumer-in-0:
          destination: bup
          group: group-iam-service
  neo4j:
    repositories:
      type: imperative
    uri: bolt://localhost:7687
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          iam-service-client-credentials:
            provider: spring
            client-id: iam-service
            client-secret: iama-service-secret
            authorization-grant-type: client_credentials
            scope: iam.facultad
            client-name: iam-service-client-credentials
        provider:
          spring:
            issuer-uri: http://auth-service:9000
            # ^ for localNoDocker & localCmdLine an 'auth' must be declared in hosts file
        rest:
          client-id: iam-service-client-credentials
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:9000

# Also needed by AuthServerUserLookupService
security:
  clientId: iam-service

logging:
  level:
    com:
      netflix: WARN
      springframework:
        web: WARN
        core:
          codec:
            StringDecoder: TRACE
      ailegorreta:
        iamservice: WARN
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

info:
  system: Marketplace AILegorreta

# Monitoring with actuator
management:
  endpoints:
    web:
      exposure:
        include: iam, env, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

iam-service:
  test: false

ailegorreta:
  neo4j:
    flyway:
      locations: /db/neo4j/migration # Script to initialize iamDB (also in auth-service)
